on: pull_request

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
        - name: Verificando repositório Git
          uses: actions/checkout@v2

        - name: Instalando node na versão 12
          uses: actions/setup-node@v1
          with:
            node-version: 12

        - name: Instalando dependências
          run: npm install
          
        - name: Verificando erros de Lint
          run: npx eslint . 